// Would You Rather Questions
export const wouldYouRatherQuestions = [
  { optionA: "Have the ability to fly", optionB: "Have the ability to read minds" },
  { optionA: "Live without music", optionB: "Live without movies" },
  { optionA: "Be able to speak every language", optionB: "Be able to talk to animals" },
  { optionA: "Have unlimited money", optionB: "Have unlimited time" },
  { optionA: "Always be 10 minutes late", optionB: "Always be 20 minutes early" },
  { optionA: "Never use social media again", optionB: "Never watch TV again" },
  { optionA: "Have a pause button for life", optionB: "Have a rewind button for life" },
  { optionA: "Be famous", optionB: "Be the best friend of someone famous" },
  { optionA: "Live in space", optionB: "Live underwater" },
  { optionA: "Have free WiFi everywhere", optionB: "Have free coffee everywhere" },
  { optionA: "Be invisible", optionB: "Be able to teleport" },
  { optionA: "Have a personal chef", optionB: "Have a personal chauffeur" },
  { optionA: "Always have to whisper", optionB: "Always have to shout" },
  { optionA: "Know how you will die", optionB: "Know when you will die" },
  { optionA: "Be stuck in a horror movie", optionB: "Be stuck in a romantic comedy" },
  { optionA: "Have spaghetti for hair", optionB: "Sweat maple syrup" },
  { optionA: "Fight 100 duck-sized horses", optionB: "Fight 1 horse-sized duck" },
  { optionA: "Give up cheese forever", optionB: "Give up chocolate forever" },
  { optionA: "Have a talking cat", optionB: "Have a flying dog" },
  { optionA: "Be able to control fire", optionB: "Be able to control water" },
  { optionA: "Live in a treehouse", optionB: "Live in a castle" },
  { optionA: "Have super strength", optionB: "Have super speed" },
  { optionA: "Never sleep again", optionB: "Never eat again" },
  { optionA: "Be extremely lucky", optionB: "Be extremely skilled" },
  { optionA: "Have a personal robot", optionB: "Have a magic wand" },
  { optionA: "Travel to the past", optionB: "Travel to the future" },
  { optionA: "Be fluent in all languages", optionB: "Be a master of every instrument" },
  { optionA: "Have unlimited storage on all devices", optionB: "Have unlimited battery life" },
  { optionA: "Always get green lights", optionB: "Never wait in line again" },
  { optionA: "Be able to breathe underwater", optionB: "Be able to survive in space" },
  { optionA: "Have your dream job", optionB: "Win the lottery" },
  { optionA: "Be the funniest person in the room", optionB: "Be the smartest person in the room" },
  { optionA: "Live without AC/heating", optionB: "Live without internet" },
  { optionA: "Have a photographic memory", optionB: "Have perfect intuition" },
  { optionA: "Be a vampire", optionB: "Be a werewolf" },
  { optionA: "Speak all languages", optionB: "Play all instruments" },
  { optionA: "Have a personal island", optionB: "Have a penthouse in NYC" },
  { optionA: "Be able to change your past", optionB: "Be able to see the future" },
  { optionA: "Have unlimited first class flights", optionB: "Have unlimited 5-star hotel stays" },
  { optionA: "Be a famous musician", optionB: "Be a famous actor" },
  { optionA: "Always be cold", optionB: "Always be hot" },
  { optionA: "Have X-ray vision", optionB: "Have super hearing" },
  { optionA: "Eat only pizza forever", optionB: "Eat only tacos forever" },
  { optionA: "Be a superhero", optionB: "Be a wizard" },
  { optionA: "Live in Harry Potter world", optionB: "Live in Star Wars galaxy" },
  { optionA: "Have a dragon", optionB: "Have a unicorn" },
  { optionA: "Be immortal", optionB: "Have 9 lives like a cat" },
  { optionA: "Have no homework ever", optionB: "Be paid for doing homework" },
  { optionA: "Be a time traveler", optionB: "Be a space explorer" },
  { optionA: "Live in a world with dinosaurs", optionB: "Live in a world with aliens" },
]

// Random Challenges
export const challenges = [
  "Do 15 jumping jacks right now!",
  "Text someone you haven't talked to in a while",
  "Draw a self-portrait in 60 seconds",
  "Do your best celebrity impression",
  "Take a selfie making your silliest face",
  "Send a meme to a random contact",
  "Write a haiku about your day",
  "Do a 30-second plank",
  "List 5 things you're grateful for",
  "Compliment a stranger online",
  "Try to touch your toes for 30 seconds",
  "Drink a full glass of water",
  "Send a voice note to a friend",
  "Do 10 push-ups (or modified push-ups)",
  "Write down 3 goals for this week",
  "Clean one small area of your space",
  "Do a random act of kindness",
  "Learn a new word and use it today",
  "Take 5 deep breaths with your eyes closed",
  "Text your mom or dad that you love them",
  "Make a paper airplane and fly it",
  "Do your happy dance for 30 seconds",
  "Write a 6-word story",
  "Stand on one foot for 1 minute",
  "Name 10 countries in 30 seconds",
  "Sing the chorus of your favorite song",
  "Do 20 calf raises",
  "Think of 5 things that start with 'Z'",
  "Give yourself a pep talk in the mirror",
  "Stretch your arms above your head for 30 seconds",
]

// Meme text overlays
export const memeTopTexts = [
  "WHEN YOU",
  "ME TRYING TO",
  "THAT FACE WHEN",
  "NOBODY:",
  "POV:",
  "WHEN THE",
  "ME AT 3AM",
  "WHEN YOUR BOSS",
  "TRYING TO BE",
  "WHEN MONDAY",
  "WHEN FRIDAY",
  "MY FACE WHEN",
  "CURRENT MOOD:",
  "WHEN SOMEONE",
  "ME PRETENDING",
]

export const memeBottomTexts = [
  "UNDERSTAND THE ASSIGNMENT",
  "BE A PRODUCTIVE MEMBER OF SOCIETY",
  "FIND THE MOTIVATION",
  "ABSOLUTELY EVERYONE:",
  "IT'S ALMOST THE WEEKEND",
  "DEADLINE IS TOMORROW",
  "LOOKING FOR SNACKS",
  "SAYS 'WE NEED TO TALK'",
  "PROFESSIONAL AND RESPONSIBLE",
  "HITS DIFFERENT",
  "FINALLY ARRIVES",
  "I SEE FREE FOOD",
  "MOOD",
  "ASKS 'ARE YOU OKAY?'",
  "TO HAVE IT TOGETHER",
]

// This or That Polls
export const thisOrThatPolls = [
  { optionA: "Coffee", optionB: "Tea", votesA: 67, votesB: 33 },
  { optionA: "Cats", optionB: "Dogs", votesA: 48, votesB: 52 },
  { optionA: "Beach", optionB: "Mountains", votesA: 55, votesB: 45 },
  { optionA: "Morning person", optionB: "Night owl", votesA: 35, votesB: 65 },
  { optionA: "Sweet", optionB: "Savory", votesA: 42, votesB: 58 },
  { optionA: "Movies", optionB: "TV Shows", votesA: 38, votesB: 62 },
  { optionA: "Summer", optionB: "Winter", votesA: 61, votesB: 39 },
  { optionA: "Books", optionB: "Podcasts", votesA: 54, votesB: 46 },
  { optionA: "Pizza", optionB: "Burgers", votesA: 58, votesB: 42 },
  { optionA: "Android", optionB: "iPhone", votesA: 41, votesB: 59 },
  { optionA: "Pancakes", optionB: "Waffles", votesA: 44, votesB: 56 },
  { optionA: "Introvert", optionB: "Extrovert", votesA: 62, votesB: 38 },
  { optionA: "City life", optionB: "Country life", votesA: 51, votesB: 49 },
  { optionA: "Call", optionB: "Text", votesA: 23, votesB: 77 },
  { optionA: "Hot weather", optionB: "Cold weather", votesA: 45, votesB: 55 },
  { optionA: "Shower", optionB: "Bath", votesA: 72, votesB: 28 },
  { optionA: "Early bird", optionB: "Night owl", votesA: 34, votesB: 66 },
  { optionA: "Chocolate", optionB: "Vanilla", votesA: 63, votesB: 37 },
  { optionA: "Sushi", optionB: "Steak", votesA: 47, votesB: 53 },
  { optionA: "Rain", optionB: "Sunshine", votesA: 31, votesB: 69 },
]

// Boredom messages
export const boredomMessages: Record<number, { message: string; suggestion: string }> = {
  0: { message: "You're not even bored? Why are you here then?", suggestion: "cat-meme" },
  1: { message: "Just a tiny bit restless, huh?", suggestion: "useless-facts" },
  2: { message: "The boredom is setting in...", suggestion: "jokes" },
  3: { message: "Time is crawling...", suggestion: "this-or-that" },
  4: { message: "Starting to feel the void...", suggestion: "would-you-rather" },
  5: { message: "Peak procrastination mode!", suggestion: "mini-games" },
  6: { message: "Boredom level: CRITICAL", suggestion: "challenges" },
  7: { message: "You've mastered the art of doing nothing!", suggestion: "mini-games" },
  8: { message: "At this point, watching paint dry sounds exciting", suggestion: "cat-meme" },
  9: { message: "Professional time waster detected!", suggestion: "challenges" },
  10: { message: "MAXIMUM BOREDOM ACHIEVED! You are a legend!", suggestion: "surprise" },
}

// Funny loading messages
export const loadingMessages = [
  "Generating pointless content...",
  "Consulting the procrastination gods...",
  "Wasting precious milliseconds...",
  "Loading cat-egory A content...",
  "Maximizing your unproductivity...",
  "Fetching useless data...",
  "Optimizing time wastage...",
  "Deploying distractions...",
  "Calibrating boredom levels...",
  "Summoning the void...",
]
